// resources/js/components/notes/assist-panel.tsx
import { useState } from 'react';
import { AtomizeAssist } from '@/components/notes/atomize-assist';
import { FormulateAssist } from '@/components/notes/formulate-assist';
import { TriageAssist } from '@/components/notes/triage-assist';
import type { Note, PhaseOption } from '@/types';

type Props = {
    note: Note;
    suggestedPhase: string;
    phases: PhaseOption[];
};

/**
 * The assist panel: one tab per playbook phase, with the suggested phase marked
 * and active on mount. Which phase is active is ephemeral client state — a tab
 * switch only swaps the shown child, it never touches or navigates the note.
 * Triage, Atomize, and Formulate are wired today; the rest show a quiet placeholder.
 */
export function AssistPanel({ note, suggestedPhase, phases }: Props) {
    const [activePhase, setActivePhase] = useState(suggestedPhase);

    return (
        <section
            className="flex flex-col gap-3 border-t pt-4"
            data-test="assist-panel"
            aria-label="Assists"
        >
            <h2 className="text-sm font-semibold text-muted-foreground">
                Assists
            </h2>

            <div className="flex flex-wrap gap-1.5" role="tablist">
                {phases.map((phase) => {
                    const isSuggested = phase.value === suggestedPhase;
                    const isActive = phase.value === activePhase;

                    return (
                        <button
                            key={phase.value}
                            type="button"
                            role="tab"
                            aria-selected={isActive}
                            onClick={() => setActivePhase(phase.value)}
                            data-test={`phase-tab-${phase.value}`}
                            className={
                                isActive
                                    ? 'rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground'
                                    : 'rounded-md border px-2 py-1 text-xs text-muted-foreground hover:text-foreground'
                            }
                        >
                            {phase.label}
                            {isSuggested ? (
                                <span className="ml-1 opacity-70">
                                    · suggested
                                </span>
                            ) : null}
                        </button>
                    );
                })}
            </div>

            <div data-test="assist-active">
                <ActiveAssist activePhase={activePhase} note={note} />
            </div>
        </section>
    );
}

/** Maps the active phase to its wired child, falling back to the placeholder. */
function ActiveAssist({
    activePhase,
    note,
}: {
    activePhase: string;
    note: Note;
}) {
    switch (activePhase) {
        case 'triage':
            return <TriageAssist note={note} />;
        case 'atomize':
            return <AtomizeAssist note={note} />;
        case 'formulate':
            return <FormulateAssist note={note} />;
        default:
            return <PhasePlaceholder />;
    }
}

function PhasePlaceholder() {
    return (
        <div
            className="rounded-xl border border-dashed p-6 text-center text-muted-foreground"
            data-test="phase-placeholder"
        >
            <p className="font-medium">Nothing here yet.</p>
            <p className="text-sm">This assist is on the way.</p>
        </div>
    );
}

// resources/js/components/notes/AssistPanel.svelte
<script lang="ts">
    import AtomizeAssist from '@/components/notes/AtomizeAssist.svelte';
    import ClusterProjectAssist from '@/components/notes/ClusterProjectAssist.svelte';
    import ConnectAssist from '@/components/notes/ConnectAssist.svelte';
    import FormulateAssist from '@/components/notes/FormulateAssist.svelte';
    import MakeFindableAssist from '@/components/notes/MakeFindableAssist.svelte';
    import StructureAssist from '@/components/notes/StructureAssist.svelte';
    import TriageAssist from '@/components/notes/TriageAssist.svelte';
    import { getAssistPanelState } from '@/pages/notes/AssistPanelState.svelte';
    import type { Note } from '@/types';

    let { note }: { note: Note } = $props();

    const panel = getAssistPanelState();
</script>

<section class="flex flex-col gap-3 border-t pt-4" data-test="assist-panel" aria-label="Assists">
    <h2 class="text-sm font-semibold text-muted-foreground">Assists</h2>

    <div class="flex flex-wrap gap-1.5" role="tablist">
        {#each panel.phases as phase (phase.value)}
            {@const isSuggested = phase.value === panel.suggestedPhase}
            {@const isActive = phase.value === panel.activePhase}
            <button
                type="button"
                role="tab"
                aria-selected={isActive}
                onclick={() => panel.setPhase(phase.value)}
                data-test={`phase-tab-${phase.value}`}
                class={isActive
                    ? 'rounded-md bg-primary px-2 py-1 text-xs font-medium text-primary-foreground'
                    : 'rounded-md border px-2 py-1 text-xs text-muted-foreground hover:text-foreground'}
            >
                {phase.label}
                {#if isSuggested}
                    <span class="ml-1 opacity-70">· suggested</span>
                {/if}
            </button>
        {/each}
    </div>

    <div data-test="assist-active">
        {#if panel.activePhase === 'triage'}
            <TriageAssist {note} />
        {:else if panel.activePhase === 'atomize'}
            <AtomizeAssist {note} />
        {:else if panel.activePhase === 'formulate'}
            <FormulateAssist {note} />
        {:else if panel.activePhase === 'connect'}
            <ConnectAssist {note} />
        {:else if panel.activePhase === 'make_findable'}
            <MakeFindableAssist {note} />
        {:else if panel.activePhase === 'structure'}
            <StructureAssist {note} />
        {:else if panel.activePhase === 'cluster_project'}
            <ClusterProjectAssist {note} />
        {/if}
    </div>
</section>
