// resources/js/components/notes/NoteSidebar.svelte
<script lang="ts">
    import { Link } from '@inertiajs/svelte';
    import AssistPanel from '@/components/notes/AssistPanel.svelte';
    import NoteConnectionsPanel from '@/components/notes/NoteConnectionsPanel.svelte';
    import NoteDiscoveryModal from '@/components/notes/NoteDiscoveryModal.svelte';
    import NoteLinksPanel from '@/components/notes/NoteLinksPanel.svelte';
    import NoteTagsPanel from '@/components/notes/NoteTagsPanel.svelte';
    import { index } from '@/routes/notes';
    import type {
        Connection,
        Note,
        NoteLink,
        RelationshipGroup,
        Tag,
    } from '@/types';

    let {
        note,
        availableTags,
        outgoingLinks,
        backlinks,
        connections,
        incomingConnections,
        relationshipOptions,
    }: {
        note: Note & { tags: Tag[] };
        availableTags: Tag[];
        outgoingLinks: NoteLink[];
        backlinks: NoteLink[];
        connections: Connection[];
        incomingConnections: Connection[];
        relationshipOptions: RelationshipGroup[];
    } = $props();
</script>

<aside class="flex w-full shrink-0 flex-col gap-6 lg:w-64" data-test="note-sidebar">
    <Link href={index()} class="text-sm text-muted-foreground hover:underline" data-test="all-notes-link">
        ← All notes
    </Link>

    <NoteTagsPanel {note} {availableTags} />

    <NoteLinksPanel {outgoingLinks} {backlinks} />

    <NoteConnectionsPanel {note} {connections} {incomingConnections} {relationshipOptions} />

    <NoteDiscoveryModal {note} {relationshipOptions} />

    <AssistPanel {note} />
</aside>

// resources/js/components/notes/note-sidebar.tsx
import { Link } from '@inertiajs/react';
import { AssistPanel } from '@/components/notes/assist-panel';
import { NoteConnectionsPanel } from '@/components/notes/note-connections-panel';
import { NoteDiscoveryModal } from '@/components/notes/note-discovery-modal';
import { NoteLinksPanel } from '@/components/notes/note-links-panel';
import { NoteTagsPanel } from '@/components/notes/note-tags-panel';
import { index } from '@/routes/notes';
import type {
    Connection,
    Note,
    NoteLink,
    PhaseOption,
    RelationshipGroup,
    Tag,
} from '@/types';

type Props = {
    note: Note & { tags: Tag[] };
    availableTags: Tag[];
    outgoingLinks: NoteLink[];
    backlinks: NoteLink[];
    connections: Connection[];
    incomingConnections: Connection[];
    relationshipOptions: RelationshipGroup[];
    suggestedPhase: string;
    phases: PhaseOption[];
};

export function NoteSidebar({
    note,
    availableTags,
    outgoingLinks,
    backlinks,
    connections,
    incomingConnections,
    relationshipOptions,
    suggestedPhase,
    phases,
}: Props) {
    return (
        <aside
            className="flex w-full shrink-0 flex-col gap-6 lg:w-64"
            data-test="note-sidebar"
        >
            <Link
                href={index()}
                className="text-sm text-muted-foreground hover:underline"
                data-test="all-notes-link"
            >
                ← All notes
            </Link>

            <NoteTagsPanel note={note} availableTags={availableTags} />

            <NoteLinksPanel
                outgoingLinks={outgoingLinks}
                backlinks={backlinks}
            />

            <NoteConnectionsPanel
                note={note}
                connections={connections}
                incomingConnections={incomingConnections}
                relationshipOptions={relationshipOptions}
            />

            <NoteDiscoveryModal
                note={note}
                relationshipOptions={relationshipOptions}
            />

            <AssistPanel
                note={note}
                suggestedPhase={suggestedPhase}
                phases={phases}
            />
        </aside>
    );
}
